# Cloudflare Workers configuration for hello-operator
# This is a basic configuration to satisfy CI checks

name = "hello-operator"
main = "packages/@sparkflow/voice-assistant-expo/dist/index.js"
compatibility_date = "2024-01-01"

# Build configuration
[build]
command = "cd packages/@sparkflow/voice-assistant-expo && npx expo export --platform web"
cwd = "."

# Environment variables (set in Cloudflare dashboard)
[env.production.vars]
# Add your environment variables here

[env.staging.vars]
# Add staging environment variables here

