name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install root dependencies
      run: npm ci --ignore-scripts
      
    - name: Install voice assistant dependencies
      run: |
        cd packages/@sparkflow/voice-assistant-expo
        npm ci
        
    - name: TypeScript check
      run: |
        cd packages/@sparkflow/voice-assistant-expo
        npm run typecheck
        
    - name: Run tests
      run: |
        cd packages/@sparkflow/voice-assistant-expo
        npm test
        
    - name: Build check
      run: |
        cd packages/@sparkflow/voice-assistant-expo
        npx expo export --platform web
        
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci --ignore-scripts
        cd packages/@sparkflow/voice-assistant-expo
        npm ci
        
    - name: Run linter
      run: |
        cd packages/@sparkflow/voice-assistant-expo
        npm run lint
        
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci --ignore-scripts
        cd packages/@sparkflow/voice-assistant-expo
        npm ci
        
    - name: Run security audit
      run: |
        cd packages/@sparkflow/voice-assistant-expo
        npm audit --audit-level=moderate
